/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

Answer = 4613732
*/

let sequence = function(maxVal) {
	let array = [
		1,
		2
	]
	let next = array[0] + array[1]
	while (next < maxVal) {
		array.push(next);
		next = array[array.length - 1] + array[array.length - 2];
	}
	return array;
}

console.log(sequence(4000000));

let result = sequence(4000000).filter(function(term) {
		return term % 2 === 0;
	})
	.reduce(function(sum, term) {
		return sum + term
	}, 0);
console.log(result)
